repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: webtor
  url: https://charts.webtor.io

releases:
- name: redis
  namespace: webtor
  chart: bitnami/redis
  values:
    - usePassword: false
    - cluster:
        enabled: false
    - master:
        persistence:
          enabled: false
- name: content-prober
  namespace: webtor
  chart: webtor/content-prober
  version: 0.1.1
  missingFileHandler: Warn
  values:
    - image:
        tag: facff27ad4153bcf10ed015666e1f46dfd32ea14
    - content-prober.yaml
- name: magnet2torrent
  namespace: webtor
  chart: webtor/magnet2torrent
  version: 0.1.1
  missingFileHandler: Warn
  values:
    - image:
        tag: bc1a7e4bcbba0cfeeb7f6e38381d7de95a444457
    - magnet2torrent.yaml
- name: external-proxy
  namespace: webtor
  chart: webtor/external-proxy
  version: 0.1.1
  missingFileHandler: Warn
  values:
    - image:
        tag: 30e3733a4ce77a54ae77dc9f73fa8d90fc72db00
    - external-proxy.yaml
- name: video-info
  namespace: webtor
  chart: webtor/video-info
  version: 0.1.4
  missingFileHandler: Warn
  values:
    - image:
        tag: ea184673c0193a87b32b11c8a68ad90bbddd4778
    - video-info.yaml
- name: torrent-archiver
  namespace: webtor
  chart: webtor/torrent-archiver
  version: 0.1.3
  missingFileHandler: Warn
  values:
    - image:
        tag: 3937bb4ec516fd277b65078de9804e70f97d1a8c
    - torrent-archiver.yaml
- name: torrent-store
  namespace: webtor
  chart: webtor/torrent-store
  version: 0.1.3
  missingFileHandler: Warn
  values:
    - image:
        tag: 14c004567eea8675462f65bb4b9e0058b3edfe21
    - redis:
        enabled: true
    - torrent-store.yaml
- name: srt2vtt
  namespace: webtor
  chart: webtor/srt2vtt
  version: 0.1.1
  missingFileHandler: Warn
  values:
    - image:
        tag: 273965d8b3f54ac5d1490ad99efd2d1c898f6c65
    - srt2vtt.yaml
- name: job-cleaner
  namespace: webtor
  chart: webtor/job-cleaner
  version: 0.1.3
  missingFileHandler: Warn
  values:
    - image:
        tag: f91ef1cde4d60f8bea3d0c805d8adbce1d21a99a
    - job-cleaner.yaml
- name: web-ui
  namespace: webtor
  chart: webtor/webtor-web-ui
  version: 0.1.7
  missingFileHandler: Warn
  values:
    - image:
        tag: edd9147769df40b33ec241594b00371cdf04a554
    - service:
        type: NodePort
    - web-ui.yaml
- name: torrent-http-proxy
  namespace: webtor
  chart: webtor/torrent-http-proxy
  version: 0.1.25
  missingFileHandler: Warn
  values:
    - seeder:
        image: ghcr.io/webtor-io/torrent-web-seeder:aafcfb56ec36fa16e740720f4a937991a7c5da3b
    - transcoder:
        image: ghcr.io/webtor-io/content-transcoder:f802e32f814558f78c270ba72fb674e4ae60b68a
    - service:
        type: NodePort
    - image:
        tag: 9daeeb830f0944ead091ba0307bbacbc888e26ca
    - clients.yaml
    - torrent-http-proxy.yaml
